project_id = "kywzkycqhyzdmkfokpjn"

[functions.send-approval-notification]
verify_jwt = false

[functions.send-pin]
verify_jwt = false

[functions.send-workflow-notification]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.test-wa-gateway]
verify_jwt = false

[functions.generate-database-backup]
verify_jwt = false

[functions.check-email-for-reset]
verify_jwt = false

[functions.verify-reset-otp]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.auto-archive]
verify_jwt = false

[functions.export-backup]
verify_jwt = false
